ALTER TYPE "MatchStatus" ADD VALUE IF NOT EXISTS 'CANCELLED';

ALTER TABLE "Match" ADD COLUMN IF NOT EXISTS "minute" INTEGER;
ALTER TABLE "Match" ADD COLUMN IF NOT EXISTS "lastSyncedAt" TIMESTAMP(3);
