CREATE TYPE "UserRole" AS ENUM ('USER', 'ADMIN');

ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "role" "UserRole" NOT NULL DEFAULT 'USER';
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "isHidden" BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE "Match" ADD COLUMN IF NOT EXISTS "homeTeamLogo" TEXT;
ALTER TABLE "Match" ADD COLUMN IF NOT EXISTS "awayTeamLogo" TEXT;
ALTER TABLE "Match" ADD COLUMN IF NOT EXISTS "country" TEXT;
ALTER TABLE "Match" ADD COLUMN IF NOT EXISTS "round" TEXT;
ALTER TABLE "Match" ADD COLUMN IF NOT EXISTS "source" TEXT NOT NULL DEFAULT 'mock';
ALTER TABLE "Match" ADD COLUMN IF NOT EXISTS "providerHomeScore" INTEGER;
ALTER TABLE "Match" ADD COLUMN IF NOT EXISTS "providerAwayScore" INTEGER;
ALTER TABLE "Match" ADD COLUMN IF NOT EXISTS "providerStatus" "MatchStatus";
ALTER TABLE "Match" ADD COLUMN IF NOT EXISTS "providerUpdatedAt" TIMESTAMP(3);
ALTER TABLE "Match" ADD COLUMN IF NOT EXISTS "resultSource" TEXT NOT NULL DEFAULT 'PROVIDER';
ALTER TABLE "Match" ADD COLUMN IF NOT EXISTS "adminHomeScore" INTEGER;
ALTER TABLE "Match" ADD COLUMN IF NOT EXISTS "adminAwayScore" INTEGER;
ALTER TABLE "Match" ADD COLUMN IF NOT EXISTS "adminStatus" "MatchStatus";
ALTER TABLE "Match" ADD COLUMN IF NOT EXISTS "adminResultUpdatedAt" TIMESTAMP(3);
ALTER TABLE "Match" ADD COLUMN IF NOT EXISTS "adminResultUpdatedById" TEXT;
ALTER TABLE "Match" ADD COLUMN IF NOT EXISTS "adminNote" TEXT;
